import random
class Enemies:
    def __init__(self,name,hp,at,df,xpamt,g):
        self.name=name
        self.hp=hp
        self.at=at
        self.df=df
        self.xpamt=xpamt
        self.g=g
    def hplost(self,dmg):
        self.hp-=dmg
        print(f"{self.name} has taken {dmg} damage.")
    def fight(self,opponent,opponentdf):
        r=random.randint(1,3)
        self.damage=round(self.at-opponent-opponentdf+r)
    def check(self):
        print(f"{self.name}: {self.at} Attack {self.df} Defense")
RuinsEnemiesList=["FirstFroggit","OtherFroggits","Whimsun","Moldsmal","Vegetoid","Migosp","Loox","Napstablook","Toriel"]
SnowdinEnemiesList=["Snowdrake","Chilldrake","Ice Cap","Doggo","Lesser Dog","Jerry","Dogamy and Dogaresa","Gyftrot","Glyde","Greater Dog","papaya man"]
WaterfallEnemiesList=["Aaron","Woshua","Moldsmal","Moldsbygg","Shyren","Monster Kid","fish"]
HotlandEnemiesList=["Vulcan","Tsunderplane","Pyrope","Royal Guards","spider"]
CoreEnemiesList=["Madjick","Knight Knight","Final Froggit","Whimsalot","Astigmatism","mtt neo"]
NewHomeEnemiesList=["brother of papaya","asgore"]
YellowBossesList=["Ceroba Ketsukane","Martlet","Marlet","Axis","Dalv","Decibat","YellowAsgore"]
RuinsEnemies={
    "FirstFroggit":{
        "name":"Froggit",
        "hp":20,
        "at":4,
        "df":1,
        "xpamt":10,
        "g":20,
    },
    "OtherFroggits":{
        "name":"Froggit",
        "hp":30,
        "at":4,
        "df":4,
        "xpamt":3,
        "g":2,
    },
    "Whimsun":{
        "name":"Whimsun",
        "hp":10,
        "at":4,
        "df":0,
        "xpamt":2,
        "g":2,
    },
    "Moldsmal":{
        "name":"Moldsmal",
        "hp":50,
        "at":4,
        "df":0,
        "xpamt":3,
        "g":3,
    },
    "Vegetoid":{
        "name":"Vegetoid",
        "hp":72,
        "at":5,
        "df":0,
        "xpamt":6,
        "g":1,
    },
    "Migosp":{
        "name":"Migosp",
        "hp":40,
        "at":5,
        "df":4,
        "xpamt":5,
        "g":2,
    },
    "Loox":{
        "name":"Loox",
        "hp":50,
        "at":5,
        "df":4,
        "xpamt":7,
        "g":5,
    },
    "Napstablook":{
        "name":"Napstablook",
        "hp":88,
        "at":5,
        "df":4,
        "xpamt":0,
        "g":0,
    },
    "Toriel":{
        "name":"Toriel",
        "hp":440,
        "at":6,
        "df":-9999,
        "xpamt":150,
        "g":0,
    }
}
SnowdinEnemies={
    "Snowdrake":{
        "name":"Snowdrake",
        "hp":74,
        "at":6,
        "df":2,
        "xpamt":22,
        "g":18,
    },
    "Chilldrake":{
        "name":"Chilldrake",
        "hp":74,
        "at":6,
        "df":2,
        "xpamt":22,
        "g":18,
    },
    "Ice Cap":{
        "name":"Ice Cap",
        "hp":48,
        "at":6,
        "df":0,
        "xpamt":17,
        "g":17,
    },
    "Doggo":{
        "name":"Doggo",
        "hp":70,
        "at":6,
        "df":1,
        "xpamt":30,
        "g":30,
    },
    "Lesser Dog":{
        "name":"Lesser Dog",
        "hp":60,
        "at":6,
        "df":0,
        "xpamt":18,
        "g":15,
    },
    "Jerry":{
        "name":"Jerry",
        "hp":80,
        "at":1,
        "df":8,
        "xpamt":1,
        "g":55,
    },
    "Dogamy and Dogaressa":{
        "name":"Dogamy and Dogaressa",
        "hp":216,
        "at":6,
        "df":4,
        "xpamt":60,
        "g":50,
    },
    "Gyftrot":{
        "name":"Gyftrot",
        "hp":114,
        "at":7,
        "df":3,
        "xpamt":35,
        "g":30,
    },
    "Glyde":{
        "name":"Glyde",
        "hp":220,
        "at":9,
        "df":-20,
        "xpamt":100,
        "g":140,
    },
    "Greater Dog":{
        "name":"Greater Dog",
        "hp":105,
        "at":6,
        "df":4,
        "xpamt":80,
        "g":60,
    },
    "papaya man":{
        "name":"Papyrus",
        "hp":680,
        "at":3,
        "df":-20000,
        "xpamt":200,
        "g":0,
    }
}
WaterfallEnemies={
    "Aaron":{
        "name":"Aaron",
        "hp":98,
        "at":7,
        "df":2,
        "xpamt":52,
        "g":25,
    },
    "Woshua":{
        "name":"Woshua",
        "hp":70,
        "at":7,
        "df":1,
        "xpamt":52,
        "g":25,
    },
    "Moldsmal":{
        "name":"Moldsmal",
        "hp":50,
        "at":7,
        "df":0,
        "xpamt":3,
        "g":1,
    },
    "Moldbygg":{
        "name":"Moldbygg",
        "hp":70,
        "at":7,
        "df":4,
        "xpamt":46,
        "g":30,
    },
    "Monster Kid":{
        "name":"Monster Kid",
        "hp":100,
        "at":11,
        "df":-200,
        "xpamt":0,
        "g":0,
    },
    "Shyren":{
        "name":"Shyren",
        "hp":66,
        "at":7,
        "df":2,
        "xpamt":52,
        "g":25,
    },
    "fish":{
        "name":"Undyne",
        "hp":23000,
        "at":12,
        "df":5,
        "xpamt":1500,
        "g":0,
    },
}
HotlandEnemies={
    "Vulkin":{
        "name":"Vulkin",
        "hp":20,
        "at":8,
        "df":-10,
        "xpamt":70,
        "g":50,
    },
    "Tsunderplane":{
        "name":"Tsunderplane",
        "hp":80,
        "at":8,
        "df":6,
        "xpamt":95,
        "g":45,
    },
    "Pyrope":{
        "name":"Pyrope",
        "hp":110,
        "at":8,
        "df":1,
        "xpamt":80,
        "g":40,
    },
    "Royal Guards":{
        "name":"Royal Guards",
        "hp":300,
        "at":8,
        "df":4,
        "xpamt":220,
        "g":110,
    },
    "spider":{
        "name":"Muffet",
        "hp":1250,
        "at":8,
        "df":0,
        "xpamt":300,
        "g":"a little",
    },
}
CoreEnemies={
    "Madjick":{
        "name":"Madjick",
        "hp":190,
        "at":8,
        "df":-1,
        "xpamt":150,
        "g":120,
    },
    "Knight Knight":{
        "name":"Knight Knight",
        "hp":230,
        "at":8,
        "df":2,
        "xpamt":180,
        "g":150,
    },
    "Final Froggit":{
        "name":"Final Froggit",
        "hp":100,
        "at":8,
        "df":0,
        "xpamt":120,
        "g":80,
    },
    "Whimsalot":{
        "name":"Whimsalot",
        "hp":95,
        "at":8,
        "df":-3,
        "xpamt":110,
        "g":80,
    },
    "Astigmatism":{
        "name":"Astigmatism",
        "hp":120,
        "at":8,
        "df":-2,
        "xpamt":130,
        "g":85,
    },
    "mtt neo":{
        "name":"Mettaton NEO",
        "hp":30000,
        "at":10,
        "df":-40000,
        "xpamt":50000,
        "g":0,
    },
}
NewHomeEnemies={
    "brother of papaya":{
        "name":"Sans",
        "hp":1,
        "at":1,
        "df":1,
        "xpamt":89358357978335,
        "g":0,
    },
    "asgore":{
        "name":"Asgore",
        "hp":900,
        "at":10,
        "df":-30,
        "xpamt":0,
        "g":0,
    },
}
YellowBosses={
    "Ceroba Ketsukane":{
        "name":"Ceroba Ketsukane",
        "hp":1000,
        "at":13,
        "df":23,
        "xpamt":1500,
        "g":50,
    },
    "Martlet (Snowdin)":{
        "name":"Martlet",
        "hp":750,
        "at":12,
        "df":8,
        "xpamt":0,
        "g":0,
    },
    "Martlet (Final Battle)":{
        "name":"Martlet",
        "hp":750,
        "at":25,
        "df":40,
        "xpamt":200,
        "g":0,
    },
    "Axis":{
        "name":"Axis",
        "hp":800,
        "at":19,
        "df":15,
        "xpamt":200,
        "g":0,
    },
    "Dalv":{
        "name":"Dalv",
        "hp":240,
        "at":6,
        "df":4,
        "xpamt":120,
        "g":15,
    },
    "Decibat":{
        "name":"Decibat",
        "hp":80,
        "at":4,
        "df":5,
        "xpamt":7,
        "g":8,
    },
    "YellowAsgore":{
        "name":"Asgore",
        "hp":1,
        "at":0,
        "df":-9999,
        "xpamt":0,
        "g":0
    }
}